name = "VectorSpaceLeastSquares"
uuid = "75b2bf16-027a-4fc4-b4ae-e959163e71fc"
authors = ["Jerome Lelong <jerome.lelong@gmail.com>"]
version = "1.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Distributions = "0.25.122"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
